DROP TABLE ctlogs CASCADE;
DROP TABLE sth CASCADE;
DROP TABLE consistency_check_errors CASCADE;
DROP TABLE cert_fetch_errors CASCADE;
DROP TABLE retired_log_changed_error CASCADE;
DROP TABLE certificates CASCADE;
DROP TABLE certificate_chain CASCADE;
DROP TABLE certificate_appears_in_leaf CASCADE;
DROP TABLE certificate_dns_names CASCADE;
